# Generated by Django 3.2.2 on 2021-05-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrname', models.CharField(default='', max_length=50)),
                ('lname', models.CharField(default='', max_length=50)),
                ('bgrp', models.CharField(default='', max_length=5)),
                ('age', models.CharField(default='', max_length=100)),
                ('wt', models.CharField(default='', max_length=200)),
                ('ht', models.CharField(default='', max_length=300)),
                ('txta', models.TextField(default='')),
            ],
        ),
    ]
