# Generated by Django 3.2.2 on 2021-05-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='age',
        ),
        migrations.RemoveField(
            model_name='post',
            name='bgrp',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ht',
        ),
        migrations.RemoveField(
            model_name='post',
            name='txta',
        ),
        migrations.RemoveField(
            model_name='post',
            name='wt',
        ),
        migrations.AddField(
            model_name='post',
            name='fname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
