# Generated by Django 3.2.2 on 2021-05-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210521_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='age',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='bgrp',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='post',
            name='ht',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='txta',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='wt',
            field=models.CharField(default='', max_length=200),
        ),
    ]
