# Generated by Django 3.2.2 on 2021-05-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20210521_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='que1',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='que2',
            field=models.CharField(default='', max_length=300),
        ),
    ]
