# Generated by Django 3.2.2 on 2021-05-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20210521_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='usrname',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
